# Info that changes with each new release
# (get sha256 from https://pypi.org/project/visvis/#files)

{% set version = "1.10.0" %}
{% set sha256 = "1b6703c19b9e51c524c88901b8524b16bc071f55b00443455a568975bf22dd74" %}

package:
  name: visvis
  version: {{ version }}

source:
  fn: visvis-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/visvis/visvis-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python setup.py install
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - pyopengl

test:
  imports:
    - visvis
    - visvis.vvio
    - visvis.processing

about:
  home: https://github.com/almarklein/visvis
  doc_url: https://github.com/almarklein/visvis/wiki
  dev_url: https://github.com/almarklein/visvis
  summary: Visvis - the object oriented approach to visualization
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - almarklein
