{% set name = "visvis" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa013c62ea54ae4d170096e1fced7c3697b1d05c2fe6b38e822af0a986422a39

build:
  number: 0
  skip: true  # [py<27]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
  run:
    - python
    - numpy
    - pyopengl

# =======================
# Test configuration
# =======================
{% set test_root = "tests" %}

# - test_im_read_write: no file: vv.imread("astronaut.png")
{% set skip_keywords = [
    "test_im_read_write"
] %}

test:
  requires:
    - pip
    - pytest
  source_files:
    - {{ test_root }}
  imports:
    - visvis
    - visvis.core
    - visvis.backends
    - visvis.functions
    - visvis.processing
    - visvis.text
    - visvis.utils
    - visvis.vvmovie
    - visvis.wibjects
    - visvis.wobjects
  commands:
    - pip check
    - python -c "import visvis; print(visvis.__version__)"
    - pytest -v {{ test_root }} -k "not ({{ skip_keywords | join(' or ') }})"

about:
  home: https://github.com/almarklein/visvis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An object oriented approach to visualization of 1D to 4D data
  description: |
    Visvis is a pure Python library for visualization of 1D to 4D data in an
    object oriented way. Essentially, visvis is an object oriented layer of
    Python on top of OpenGl, thereby combining the power of OpenGl with the
    usability of Python. A Matlab-like interface in the form of a set of
    functions allows easy creation of objects.
    The successor of Visvis, Vispy, is taking shape and will eventually
    replace Visvis.
  doc_url: https://github.com/almarklein/visvis/wiki
  dev_url: https://github.com/almarklein/visvis

extra:
  recipe-maintainers:
    - almarklein
