{% set name = "visvis" %}
{% set version = "1.13.0" %}
{% set sha256 = "319d2e37c9756a029be33dc491461b8359fc52caa9c5147807eba583cafbf749" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pyopengl

test:
  imports:
    - visvis
    - visvis.processing

about:
  home: https://github.com/almarklein/visvis
  license: BSD 3-Clause
  license_family: BSD
  summary: An object oriented approach to visualization of 1D to 4D data
  description: |
    Visvis is a pure Python library for visualization of 1D to 4D data in an
    object oriented way. Essentially, visvis is an object oriented layer of
    Python on top of OpenGl, thereby combining the power of OpenGl with the
    usability of Python. A Matlab-like interface in the form of a set of
    functions allows easy creation of objects.
    The successor of Visvis, Vispy, is taking shape and will eventually
    replace Visvis.
  doc_url: https://github.com/almarklein/visvis/wiki
  dev_url: https://github.com/almarklein/visvis

extra:
  recipe-maintainers:
    - almarklein
