travis:
  secure:
    BINSTAR_TOKEN: A9Wq2+xjXdKJiUl55jjfWl2V7Mpnhp8p8ZAlw8kyszjWU5dPUB2/vAOE/72c4gP00McQaWkHlZv6wK34GCvVqc03ugtHbHbwludy+0VNNHq1QdBHXf+mkgsqXr5+ze409Ky1i7e7rBghpF1LmEUKju4+yYBI2oh88ribeGSDDyjgodc8ppG/rq6tv4AJbrzW9+zU/wFbP+0MQwS8bgMo6bz7uyhl3+yC/naONwyrXjvzohlr3nTC2ghpybpreJgAq5OcVFeeUsc3Y6zCPB90hcEPY1te2uwLOF2EJ+TyJmZqRkDN4qw0Qy7z/Lhauh5Q3g6Kd28ByPeR4JYS0Aq7We2b2Ka9mYs1d61aB2PQhiVsYUXWOr0MVXQ8uky/z7AVcgxDOs0m41ivingvYomRM/ygZ9PAIOLdhU9xJ1kCckWxqlKVxYeTS3eTq/s7usnyvi8Hy0opvBWUzDHt/WYY2z6n8ByitqqzqrprNYlWNe7JXzxjAfqWGB54rW8yuCIimuN5kmhBIUe4iW8vejjQ5zvGbir5EKocsww/T/XAVarGJ4Pbvv+0yOdFo1ElsNy3uxr3IvJ6qG28UrixOQ9A4Ka9fARxfYqNJISItZ+N8oFTC9sLiDeEAbzf/9UXrm9BE+PTJxOqmB8R+5XZ5bN/U6hDM6iVn4TBzLK4AkvCdxI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
