travis:
  secure:
    BINSTAR_TOKEN: YFa1KPL2hW/ZMDiN7+gR8UnNVkBojqRXKIfsPNZ8EwU5DecxHa2KJ3ZihGs0suA4L4E7oo8/gg8Hc2wfD4BhEE8GPwa7XPV2nSAkA/H5AGFAtXw4YJbIynpDe39cBhnymykCIWTdaawwnm+bLNm5SFpEJbzW5ei/HdJ2NWWXQQrWxhAG3neRq/rJRgvqhO7c1IREP5cuuOWylSKNoInR6XM6Sa144G6Bk/nkSvuZ/cO3eoRCcy0DFZ1g/JIbONO5dARdLgOD/hBSIvAzfwuuxm17/E7FI/PZwdMgSE0/ZDWlE5e0Crx7SZDiQzoIp6sxsRowS2phwXrJJ6Ka73LpMDwC+hgOlXqNyP23jktijCCrcvjVinhkqf1a6r9EROOvD26DZmXNgfRO3rjhISONvRZyYdUpenNZoEgasIaeNB6DnhMfFJAuFEDEflvgLKc1GIXvDZI+yqKFjBXSssJoc39KdMcw++7tNEe98g8sU2997OcgL4gS1OquDVlOvLh7KBo+x4FjYYbx5Q//OyIPwOqE6k1AD+2BJY2H1S0nwlAP3VIzV9yjZPL38UwhRKcCqde3Fzt5w/5uI/ZjQ+Gh02jDQQO3jJiZQ1bOOjbI+DqcCiDOFp3XBDpzdxyUMQ6yYDSOT3fCyBSAMbLSPhTec3sBMrazqkWpi7HsTWiMUqc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
