travis:
  secure:
    BINSTAR_TOKEN: TMTlg8cSMJun5aFyOSGTkuYJSvYpxI92qjBABnIzYJOK/tqeiZNlXNWCzaC++QSJtV/jq332YcupCWcN+BfRdyDzy6A7drDQODV1udMM4ZBg1ggOyUDQ06xakXDKQiDSMXSb0ZJaMcMhtS7yi2JISo1dzwGLTw5HhLDY1kgdPrT3UhGp3e/NloD0L+rsGrpAPbcsupARjFjO1nuaA+8stBuyiyC0f/b3RqqAr5qen2gT6r6N6x7fy+WIugWF+vVj3UgXJhZjxKifOKjASHKYVWA7kV4xraMXXj+ZfWl7a98zQZgCJt3CZq+i/t+SV4UGrDSoYRmrS2tf7I1PAi5g6ZDmycWttbfwTRdCZg9PgBFo8M54UxMKo7ZmXM6MTuU1YWazTcFHbpoFKJdSEhhLEBX5BKA9B6nA2bZXZRkFTXipdEufU6hzJ5+9aoU21JIbLDHHUfscdL8tDK0DPkgjCTWe2ARFXAtnTg+tujKP51Fr4cpgJ2VN8uEsn/BZK+LsvngiaIDD5EAWxfnoHRlOzj/1DTbQvgj0vujv98uFXByVobu9vuAicNZbOaFTpYThCKfqdA9ZBl2XO7sGXdoPuIK5FJrZjwH4MQxKfQUMcBgoBP+OgIXkah71DmJge1Br5tTOgTW3Q3Zr9koJ1T6xerdoSajYwjd6CiVbpohB2ms=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
